<div class="row">
	<div class="eight columns">
		<h2>Native Social Buttons</h2>
		<p>These are social sharing buttons that are generated by loading scripts from the social network's remote servers.</p>
		<p>Documentation: <a href="https://developers.facebook.com/docs/plugins/like-button" target="_blank">Facebook Like</a>, <a href="https://developers.facebook.com/docs/plugins/share-button" target="_blank">Facebook Share</a>, <a href="https://dev.twitter.com/docs/tweet-button" target="_blank">Twitter</a>, <a href="https://developers.google.com/+/web/+1button/" target="_blank">Google+</a>, <a href="https://developer.linkedin.com/plugins/share-plugin-generator" target="_blank">LinkedIn</a></p>

		<div class="entry-social">
			<hr />
			<ul>
				<li class="facebook-like">
					<div class="fb-like" data-href="<?php the_permalink(); ?>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
				</li><!-- /facebook-like -->
				<li class="facebook-share">
					<div class="fb-share-button" data-href="<?php the_permalink(); ?>" data-type="button_count"></div>
				</li><!-- /facebook-share -->
				<li class="twitter">
					<a href="https://twitter.com/share" class="twitter-share-button" data-url="<?php the_permalink(); ?>" data-text="<?php the_title(); ?>" data-lang="en">Tweet</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
				</li><!-- /twitter -->
				<li class="google-plus">
					<div class="g-plusone" data-size="medium" data-annotation="bubble" data-callback="googlePlusCallback" data-href="<?php the_permalink(); ?>"></div>
					<script type="text/javascript">
					  (function() {
					    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
					    po.src = 'https://apis.google.com/js/platform.js';
					    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
					  })();
					</script>
				</li><!-- /google-plus -->
				<li class="linked-in">
					<script src="//platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>
					<script type="IN/Share" data-url="<?php the_permalink(); ?>" data-counter="right"></script>
				</li><!-- /linkedin -->
			</ul>
		</div>
	</div><!--/columns-->
	<div class="eight columns">
		<h2>Custom Social Buttons</h2>
		<p>These are locally stored social sharing buttons that have hard-coded hrefs. These hrefs can also be modified with javascript to dynamically pull in page titles, etc. There should always be backup hrefs hard-coded in case JS is disabled, these can at least share something.</p>
		<p>
			<a class="fbshare" href="http://www.facebook.com/sharer.php?u=<?php echo the_permalink(); ?>&t=<?php wp_title( '-', true, 'right' ); ?>" target="_blank">Facebook Share</a>,
			<a class="twshare" href="https://twitter.com/intent/tweet?text=<?php wp_title( '-', true, 'right' ); ?>&url=<?php echo the_permalink(); ?>" target="_blank">Twitter</a>,
			<a class="gshare" href="https://plus.google.com/share?url=<?php echo the_permalink(); ?>" target="_blank">Google+</a>,
			<a class="lishare" href="http://www.linkedin.com/shareArticle?mini=true&url=<?php echo the_permalink(); ?>&title=<?php wp_title( '-', true, 'right' ); ?>" target="_blank">LinkedIn</a>,
			<a class="emshare" href="mailto:?subject=<?php wp_title( '-', true, 'right' ); ?>&body=<?php echo the_permalink(); ?>" target="_blank">Email</a>
		</p>
	</div><!--/columns-->
</div><!--/row-->